<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuarios', 'doctrine');

/**
 * BaseUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codusu
 * @property string $logusu
 * @property string $pasusu
 * @property string $tipusu
 * @property string $desusu
 * @property string $dirusu
 * @property string $telusu
 * @property string $celusu
 * @property string $codciu
 * @property string $codban
 * @property string $numcue
 * @property string $emausu
 * @property string $numtar
 * @property string $tiptar
 * @property date $fecven
 * @property string $stausu
 * @property string $titcue
 * @property string $codref
 * @property string $cedusu
 * @property string $tipcue
 * @property Doctrine_Collection $Pago
 * @property Doctrine_Collection $Pago_3
 * 
 * @method string              getCodusu() Returns the current record's "codusu" value
 * @method string              getLogusu() Returns the current record's "logusu" value
 * @method string              getPasusu() Returns the current record's "pasusu" value
 * @method string              getTipusu() Returns the current record's "tipusu" value
 * @method string              getDesusu() Returns the current record's "desusu" value
 * @method string              getDirusu() Returns the current record's "dirusu" value
 * @method string              getTelusu() Returns the current record's "telusu" value
 * @method string              getCelusu() Returns the current record's "celusu" value
 * @method string              getCodciu() Returns the current record's "codciu" value
 * @method string              getCodban() Returns the current record's "codban" value
 * @method string              getNumcue() Returns the current record's "numcue" value
 * @method string              getEmausu() Returns the current record's "emausu" value
 * @method string              getNumtar() Returns the current record's "numtar" value
 * @method string              getTiptar() Returns the current record's "tiptar" value
 * @method date                getFecven() Returns the current record's "fecven" value
 * @method string              getStausu() Returns the current record's "stausu" value
 * @method string              getTitcue() Returns the current record's "titcue" value
 * @method string              getCodref() Returns the current record's "codref" value
 * @method string              getCedusu() Returns the current record's "cedusu" value
 * @method string              getTipcue() Returns the current record's "tipcue" value
 * @method Doctrine_Collection getPago()   Returns the current record's "Pago" collection
 * @method Doctrine_Collection getPago3()  Returns the current record's "Pago_3" collection
 * @method Usuarios            setCodusu() Sets the current record's "codusu" value
 * @method Usuarios            setLogusu() Sets the current record's "logusu" value
 * @method Usuarios            setPasusu() Sets the current record's "pasusu" value
 * @method Usuarios            setTipusu() Sets the current record's "tipusu" value
 * @method Usuarios            setDesusu() Sets the current record's "desusu" value
 * @method Usuarios            setDirusu() Sets the current record's "dirusu" value
 * @method Usuarios            setTelusu() Sets the current record's "telusu" value
 * @method Usuarios            setCelusu() Sets the current record's "celusu" value
 * @method Usuarios            setCodciu() Sets the current record's "codciu" value
 * @method Usuarios            setCodban() Sets the current record's "codban" value
 * @method Usuarios            setNumcue() Sets the current record's "numcue" value
 * @method Usuarios            setEmausu() Sets the current record's "emausu" value
 * @method Usuarios            setNumtar() Sets the current record's "numtar" value
 * @method Usuarios            setTiptar() Sets the current record's "tiptar" value
 * @method Usuarios            setFecven() Sets the current record's "fecven" value
 * @method Usuarios            setStausu() Sets the current record's "stausu" value
 * @method Usuarios            setTitcue() Sets the current record's "titcue" value
 * @method Usuarios            setCodref() Sets the current record's "codref" value
 * @method Usuarios            setCedusu() Sets the current record's "cedusu" value
 * @method Usuarios            setTipcue() Sets the current record's "tipcue" value
 * @method Usuarios            setPago()   Sets the current record's "Pago" collection
 * @method Usuarios            setPago3()  Sets the current record's "Pago_3" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuarios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuarios');
        $this->hasColumn('codusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'seq_usuarios',
             'length' => '',
             ));
        $this->hasColumn('logusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('pasusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('desusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('dirusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('telusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('celusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codciu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codban', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numcue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('emausu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numtar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tiptar', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fecven', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '25',
             ));
        $this->hasColumn('stausu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('titcue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codref', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cedusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tipcue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pago', array(
             'local' => 'codusu',
             'foreign' => 'codusu'));

        $this->hasMany('Pago as Pago_3', array(
             'local' => 'codusu',
             'foreign' => 'codven'));
    }
}