<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DepositoQuiniela', 'doctrine');

/**
 * BaseDepositoQuiniela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $coddep
 * @property string $codqui
 * @property Quiniela $Quiniela
 * @property Deposito $Deposito
 * 
 * @method string           getCoddep()   Returns the current record's "coddep" value
 * @method string           getCodqui()   Returns the current record's "codqui" value
 * @method Quiniela         getQuiniela() Returns the current record's "Quiniela" value
 * @method Deposito         getDeposito() Returns the current record's "Deposito" value
 * @method DepositoQuiniela setCoddep()   Sets the current record's "coddep" value
 * @method DepositoQuiniela setCodqui()   Sets the current record's "codqui" value
 * @method DepositoQuiniela setQuiniela() Sets the current record's "Quiniela" value
 * @method DepositoQuiniela setDeposito() Sets the current record's "Deposito" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDepositoQuiniela extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deposito_quiniela');
        $this->hasColumn('coddep', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('codqui', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quiniela', array(
             'local' => 'codqui',
             'foreign' => 'codqui'));

        $this->hasOne('Deposito', array(
             'local' => 'coddep',
             'foreign' => 'coddep'));
    }
}