<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grupo', 'doctrine');

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codgru
 * @property string $desgru
 * @property string $login
 * @property string $clave
 * @property string $codusu
 * @property Doctrine_Collection $Quiniela
 * 
 * @method string              getCodgru()   Returns the current record's "codgru" value
 * @method string              getDesgru()   Returns the current record's "desgru" value
 * @method string              getLogin()    Returns the current record's "login" value
 * @method string              getClave()    Returns the current record's "clave" value
 * @method string              getCodusu()   Returns the current record's "codusu" value
 * @method Doctrine_Collection getQuiniela() Returns the current record's "Quiniela" collection
 * @method Grupo               setCodgru()   Sets the current record's "codgru" value
 * @method Grupo               setDesgru()   Sets the current record's "desgru" value
 * @method Grupo               setLogin()    Sets the current record's "login" value
 * @method Grupo               setClave()    Sets the current record's "clave" value
 * @method Grupo               setCodusu()   Sets the current record's "codusu" value
 * @method Grupo               setQuiniela() Sets the current record's "Quiniela" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('codgru', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'seq_grupo',
             'length' => '',
             ));
        $this->hasColumn('desgru', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('login', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('clave', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Quiniela', array(
             'local' => 'codgru',
             'foreign' => 'codgru'));
    }
}