all:
  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         Todo Apuestas
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  '@sf_guard_signin'
    logout_route:                 '@sf_guard_signout'

    items:
      Ventas:
        url:    ventas
      Vendedores:
        url:    vendedor
      Registrar Quiniela:
        url:    quiniela
      Usuarios:
        url:    '@sf_guard_users'
      Permisos:
        url:    '@sf_guard_permission'


  sf_guard_plugin:
    success_signin_url:      '@home'
    success_signout_url:     '@sf_guard_signin'