<?php

/**
 * Quiniela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Quiniela extends BaseQuiniela
{
  public function getDestipqui()
  {
    if($this->tipqui=='2') return 'Paga';
    if($this->tipqui=='1') return 'Gratis';
  }

  public function getDisfecqui()
  {
    return date('d/m/Y', strtotime($this->fecqui));
  }

  public function PorValidar()
  {

    if($this->codpag==''){
      $depqui = Doctrine::getTable('DepositoQuiniela')->findOneBy('codqui', $this->codqui);
      if($depqui) return true;
      else return false;
    }else return false;

  }
}
