<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FormaPago', 'doctrine');

/**
 * BaseFormaPago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codforpag
 * @property string $desforpag
 * @property Doctrine_Collection $Pago
 * 
 * @method string              getCodforpag() Returns the current record's "codforpag" value
 * @method string              getDesforpag() Returns the current record's "desforpag" value
 * @method Doctrine_Collection getPago()      Returns the current record's "Pago" collection
 * @method FormaPago           setCodforpag() Sets the current record's "codforpag" value
 * @method FormaPago           setDesforpag() Sets the current record's "desforpag" value
 * @method FormaPago           setPago()      Sets the current record's "Pago" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFormaPago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forma_pago');
        $this->hasColumn('codforpag', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             //'sequence' => 'seq_forpag',
             'length' => '',
             ));
        $this->hasColumn('desforpag', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pago', array(
             'local' => 'codforpag',
             'foreign' => 'codforpag'));
    }
}