<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuinielaRonda1', 'doctrine');

/**
 * BaseQuinielaRonda1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codqui
 * @property string $codjue
 * @property decimal $goles1
 * @property decimal $goles2
 * @property decimal $puntos
 * @property Calendario $Calendario
 * @property Quiniela $Quiniela
 * 
 * @method string         getCodqui()     Returns the current record's "codqui" value
 * @method string         getCodjue()     Returns the current record's "codjue" value
 * @method decimal        getGoles1()     Returns the current record's "goles1" value
 * @method decimal        getGoles2()     Returns the current record's "goles2" value
 * @method decimal        getPuntos()     Returns the current record's "puntos" value
 * @method Calendario     getCalendario() Returns the current record's "Calendario" value
 * @method Quiniela       getQuiniela()   Returns the current record's "Quiniela" value
 * @method QuinielaRonda1 setCodqui()     Sets the current record's "codqui" value
 * @method QuinielaRonda1 setCodjue()     Sets the current record's "codjue" value
 * @method QuinielaRonda1 setGoles1()     Sets the current record's "goles1" value
 * @method QuinielaRonda1 setGoles2()     Sets the current record's "goles2" value
 * @method QuinielaRonda1 setPuntos()     Sets the current record's "puntos" value
 * @method QuinielaRonda1 setCalendario() Sets the current record's "Calendario" value
 * @method QuinielaRonda1 setQuiniela()   Sets the current record's "Quiniela" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseQuinielaRonda1 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiniela_ronda1');
        $this->hasColumn('codqui', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('codjue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('goles1', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
        $this->hasColumn('goles2', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
        $this->hasColumn('puntos', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Calendario', array(
             'local' => 'codjue',
             'foreign' => 'codjue'));

        $this->hasOne('Quiniela', array(
             'local' => 'codqui',
             'foreign' => 'codqui'));
    }
}