<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Banco', 'doctrine');

/**
 * BaseBanco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codban
 * @property string $desban
 * @property Doctrine_Collection $Deposito
 * 
 * @method integer             getCodban()   Returns the current record's "codban" value
 * @method string              getDesban()   Returns the current record's "desban" value
 * @method Doctrine_Collection getDeposito() Returns the current record's "Deposito" collection
 * @method Banco               setCodban()   Sets the current record's "codban" value
 * @method Banco               setDesban()   Sets the current record's "desban" value
 * @method Banco               setDeposito() Sets the current record's "Deposito" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBanco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banco');
        $this->hasColumn('codban', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'banco_codban',
             'length' => '4',
             ));
        $this->hasColumn('desban', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Deposito', array(
             'local' => 'codban',
             'foreign' => 'codban'));
    }
}