<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Quiniela', 'doctrine');

/**
 * BaseQuiniela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codqui
 * @property date $fecqui
 * @property string $tipqui
 * @property string $codgru
 * @property string $codven
 * @property decimal $puntos
 * @property string $forpag
 * @property string $codusu
 * @property decimal $numlidgol
 * @property decimal $goleqp1fin
 * @property decimal $goleqp2fin
 * @property string $codpag
 * @property Grupo $Grupo
 * @property Vendedor $Vendedor
 * @property Doctrine_Collection $QuinielaRonda1
 * @property Doctrine_Collection $QuinielaRondafinal
 * 
 * @method string              getCodqui()             Returns the current record's "codqui" value
 * @method date                getFecqui()             Returns the current record's "fecqui" value
 * @method string              getTipqui()             Returns the current record's "tipqui" value
 * @method string              getCodgru()             Returns the current record's "codgru" value
 * @method string              getCodven()             Returns the current record's "codven" value
 * @method decimal             getPuntos()             Returns the current record's "puntos" value
 * @method string              getForpag()             Returns the current record's "forpag" value
 * @method string              getCodusu()             Returns the current record's "codusu" value
 * @method decimal             getNumlidgol()          Returns the current record's "numlidgol" value
 * @method decimal             getGoleqp1fin()         Returns the current record's "goleqp1fin" value
 * @method decimal             getGoleqp2fin()         Returns the current record's "goleqp2fin" value
 * @method string              getCodpag()             Returns the current record's "codpag" value
 * @method Grupo               getGrupo()              Returns the current record's "Grupo" value
 * @method Vendedor            getVendedor()           Returns the current record's "Vendedor" value
 * @method Doctrine_Collection getQuinielaRonda1()     Returns the current record's "QuinielaRonda1" collection
 * @method Doctrine_Collection getQuinielaRondafinal() Returns the current record's "QuinielaRondafinal" collection
 * @method Quiniela            setCodqui()             Sets the current record's "codqui" value
 * @method Quiniela            setFecqui()             Sets the current record's "fecqui" value
 * @method Quiniela            setTipqui()             Sets the current record's "tipqui" value
 * @method Quiniela            setCodgru()             Sets the current record's "codgru" value
 * @method Quiniela            setCodven()             Sets the current record's "codven" value
 * @method Quiniela            setPuntos()             Sets the current record's "puntos" value
 * @method Quiniela            setForpag()             Sets the current record's "forpag" value
 * @method Quiniela            setCodusu()             Sets the current record's "codusu" value
 * @method Quiniela            setNumlidgol()          Sets the current record's "numlidgol" value
 * @method Quiniela            setGoleqp1fin()         Sets the current record's "goleqp1fin" value
 * @method Quiniela            setGoleqp2fin()         Sets the current record's "goleqp2fin" value
 * @method Quiniela            setCodpag()             Sets the current record's "codpag" value
 * @method Quiniela            setGrupo()              Sets the current record's "Grupo" value
 * @method Quiniela            setVendedor()           Sets the current record's "Vendedor" value
 * @method Quiniela            setQuinielaRonda1()     Sets the current record's "QuinielaRonda1" collection
 * @method Quiniela            setQuinielaRondafinal() Sets the current record's "QuinielaRondafinal" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseQuiniela extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiniela');
        $this->hasColumn('codqui', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'seq_quiniela',
             'length' => '',
             ));
        $this->hasColumn('fecqui', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '25',
             ));
        $this->hasColumn('tipqui', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codgru', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codven', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('puntos', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
        $this->hasColumn('forpag', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codusu', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numlidgol', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
        $this->hasColumn('goleqp1fin', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
        $this->hasColumn('goleqp2fin', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => '18',
             ));
        $this->hasColumn('codpag', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grupo', array(
             'local' => 'codgru',
             'foreign' => 'codgru'));

        $this->hasOne('Vendedor', array(
             'local' => 'codven',
             'foreign' => 'codven'));

        $this->hasMany('QuinielaRonda1', array(
             'local' => 'codqui',
             'foreign' => 'codqui'));

        $this->hasMany('QuinielaRondafinal', array(
             'local' => 'codqui',
             'foreign' => 'codqui'));
    }
}