<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ronda', 'doctrine');

/**
 * BaseRonda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codron
 * @property string $desron
 * @property Doctrine_Collection $Calendario
 * @property Doctrine_Collection $EquipoRonda
 * @property Doctrine_Collection $QuinielaRondafinal
 * 
 * @method string              getCodron()             Returns the current record's "codron" value
 * @method string              getDesron()             Returns the current record's "desron" value
 * @method Doctrine_Collection getCalendario()         Returns the current record's "Calendario" collection
 * @method Doctrine_Collection getEquipoRonda()        Returns the current record's "EquipoRonda" collection
 * @method Doctrine_Collection getQuinielaRondafinal() Returns the current record's "QuinielaRondafinal" collection
 * @method Ronda               setCodron()             Sets the current record's "codron" value
 * @method Ronda               setDesron()             Sets the current record's "desron" value
 * @method Ronda               setCalendario()         Sets the current record's "Calendario" collection
 * @method Ronda               setEquipoRonda()        Sets the current record's "EquipoRonda" collection
 * @method Ronda               setQuinielaRondafinal() Sets the current record's "QuinielaRondafinal" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRonda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ronda');
        $this->hasColumn('codron', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'seq_ronda',
             'length' => '',
             ));
        $this->hasColumn('desron', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Calendario', array(
             'local' => 'codron',
             'foreign' => 'codron'));

        $this->hasMany('EquipoRonda', array(
             'local' => 'codron',
             'foreign' => 'codron'));

        $this->hasMany('QuinielaRondafinal', array(
             'local' => 'codron',
             'foreign' => 'codron'));
    }
}