<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EquipoRonda', 'doctrine');

/**
 * BaseEquipoRonda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codeqp
 * @property string $codron
 * @property Equipo $Equipo
 * @property Ronda $Ronda
 * 
 * @method string      getCodeqp() Returns the current record's "codeqp" value
 * @method string      getCodron() Returns the current record's "codron" value
 * @method Equipo      getEquipo() Returns the current record's "Equipo" value
 * @method Ronda       getRonda()  Returns the current record's "Ronda" value
 * @method EquipoRonda setCodeqp() Sets the current record's "codeqp" value
 * @method EquipoRonda setCodron() Sets the current record's "codron" value
 * @method EquipoRonda setEquipo() Sets the current record's "Equipo" value
 * @method EquipoRonda setRonda()  Sets the current record's "Ronda" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEquipoRonda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipo_ronda');
        $this->hasColumn('codeqp', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
        $this->hasColumn('codron', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Equipo', array(
             'local' => 'codeqp',
             'foreign' => 'codeqp'));

        $this->hasOne('Ronda', array(
             'local' => 'codron',
             'foreign' => 'codron'));
    }
}