<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Traspaso', 'doctrine');

/**
 * BaseTraspaso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codtra
 * @property string $codusuold
 * @property string $codusunew
 * @property timestamp $fectra
 * @property string $codqui
 * @property Quiniela $Quiniela
 * @property Usuarios $Usuarios
 * @property Usuarios $Usuarios_3
 * 
 * @method integer   getCodtra()     Returns the current record's "codtra" value
 * @method string    getCodusuold()  Returns the current record's "codusuold" value
 * @method string    getCodusunew()  Returns the current record's "codusunew" value
 * @method timestamp getFectra()     Returns the current record's "fectra" value
 * @method string    getCodqui()     Returns the current record's "codqui" value
 * @method Quiniela  getQuiniela()   Returns the current record's "Quiniela" value
 * @method Usuarios  getUsuarios()   Returns the current record's "Usuarios" value
 * @method Usuarios  getUsuarios3()  Returns the current record's "Usuarios_3" value
 * @method Traspaso  setCodtra()     Sets the current record's "codtra" value
 * @method Traspaso  setCodusuold()  Sets the current record's "codusuold" value
 * @method Traspaso  setCodusunew()  Sets the current record's "codusunew" value
 * @method Traspaso  setFectra()     Sets the current record's "fectra" value
 * @method Traspaso  setCodqui()     Sets the current record's "codqui" value
 * @method Traspaso  setQuiniela()   Sets the current record's "Quiniela" value
 * @method Traspaso  setUsuarios()   Sets the current record's "Usuarios" value
 * @method Traspaso  setUsuarios3()  Sets the current record's "Usuarios_3" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTraspaso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('traspaso');
        $this->hasColumn('codtra', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'traspaso_codtra',
             'length' => '4',
             ));
        $this->hasColumn('codusuold', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('codusunew', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('fectra', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '25',
             ));
        $this->hasColumn('codqui', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Quiniela', array(
             'local' => 'codqui',
             'foreign' => 'codqui'));

        $this->hasOne('Usuarios', array(
             'local' => 'codusunew',
             'foreign' => 'codusu'));

        $this->hasOne('Usuarios as Usuarios_3', array(
             'local' => 'codusuold',
             'foreign' => 'codusu'));
    }
}